-   id: liquidsoap-prettier
    name: liquidsoap-prettier
    description: 'Liquidsoap script formatter'
    entry: liquidsoap-prettier --write
    language: node
    files: \.liq$
    additional_dependencies: ["liquidsoap-prettier@1.5.9"]

-   id: prettier
    name: prettier
    description: 'Prettier formatter'
    entry: prettier --write
    language: node
    files: \.(md|yml|yaml|json|js)$
    additional_dependencies: ["prettier@3.6.0"]
