-   id: liquidsoap-prettier
    name: liquidsoap-prettier
    description: 'Liquidsoap script formatter'
    entry: liquidsoap-prettier --write
    language: node
    'types': [text]
    files: "\\.liq$"
    args: []
    require_serial: false
    additional_dependencies: ["liquidsoap-prettier@1.4.8"]
    minimum_pre_commit_version: '0'
