-   id: liquidsoap-prettier
    name: liquidsoap-prettier
    description: 'Liquidsoap script formatter'
    entry: liquidsoap-prettier --write
    language: node
    files: \.liq$
    additional_dependencies: ["liquidsoap-prettier@1.5.6"]
