-   id: liquidsoap-prettier
    name: liquidsoap-prettier
    description: ''
    entry: liquidsoap-prettier --write
    language: node
    'types': [text]
    files: \.liq$,
    args: []
    require_serial: false
    additional_dependencies: ["prettier-plugin-liquidsoap"]
    minimum_pre_commit_version: '0'
